throwErrorOnExtraParameters: true
transparentTileErrorColor: "rgba(78, 78, 255, 125)"
opaqueTileErrorColor: "rgba(255, 155, 155, 0)"

pdfConfig: !pdfConfig
  author: "GTT"
  subject: "GTT Print"

templates:
  default-list: !template
    reportTemplate: default-list.jrxml

    attributes:
      custom_text: !string
        default: ""
      datasource: !datasource
        attributes:
          table: !table {}

    processors:
    - !reportBuilder
      directory: '.'
    - !createDataSource
      reportTemplate: table.jrxml
      reportKey: reportTemplate
      processors:
         - !prepareTable {}
    tableData: jrDataSource
